language: node_js
node_js:
  - "0.10"
install:
- "npm install component"
- "npm install component-test"
script:
- "node_modules/.bin/component build --dev"
- "node_modules/.bin/component-test phantom"
