ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    platform: linux
    version: latest
  - name: safari
    version: latest
  - name: ipad
    version: 9.2
  - name: microsoftedge
    version: latest
browserify:
  - transform: browserify-sass
  - transform: partialify
tunnel:
  type: ngrok
  bind_tls: true
