ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 9..latest
  - name: ipad
    version: latest
browserify:
  - transform: browserify-sass
  - transform: browserify-autoprefixer
  - transform: partialify
